### ISSUE TITLE
Generate tests from the CSVW test cases

### ISSUE THREAD

**Issue by lkitching** [Swirrl/csv2rdf#1]
Generate tests from the test cases defined in the [W3C test cases](http://w3c.github.io/csvw/tests/).

**Comment by RicSwirrl** [comment]
... and get them all to pass (in travis).

**Comment by lkitching** [comment]
This issue was initially for generating `csvw_test.clj` from the source `manifest.csv` in the w3c csvw repository. There are currently three test failures (see #9 #10 #11).
