### ISSUE TITLE
Define a 'minimal plus' mode

### ISSUE THREAD

**Issue by lkitching** [Swirrl/csv2rdf#17]
The 'minimal' mode defined in the CSVW specification does not output notes or annotations for tables or tablegroups defined within the metadata. These are output in standard mode, but standard mode also outputs statements describing the structure of the tabular data. Define an additional mode which works like standard mode but which also outputs notes and annotations for tables and tablegroups in the metadata when they specify an `@id`.

**Comment by Robsteranium** [comment]
What about calling this `annotated` mode? That might be a bit clearer about what's included, although it doesn't necessarily show that it falls between `minimal` and `standard`... perhaps `minimal-plus-annotaions`?

**Comment by lkitching** [comment]
I think `annotated` is fine, this is a non-standard mode so we just need to document what it does.

**Comment by Robsteranium** [comment]
Closed with PR #18
