### ISSUE TITLE
Infer RDF format in csv->rdf->file

### ISSUE THREAD

**Issue by lkitching** [Swirrl/csv2rdf#28]
`csvw/csv->rdf->file` currently always writes turtle to the output file. Update it to try to infer the RDF format from the file extension and use turtle as the default if the format could not be inferred.

**Comment by berazo29** [comment]
is this feature added?

**Comment by lkitching** [comment]
@berazo29 - Yes this has been implemented now, the format is inferred  [here](https://github.com/Swirrl/csv2rdf/blob/00626ceb43d66d1aa3b35054d06e6fb91e659e68/src/csv2rdf/csvw.clj#L84). If you use e.g. 

```clojure
(csv->rdf->file (io/file "input.csv") nil (io/file "output.nt") {})
```

it should write NTriples to the output file.
