### ISSUE TITLE
Allow lower-case e in floating point exponents

### ISSUE THREAD

**Issue by lkitching** [Swirrl/csv2rdf#46]
The specification only requires `E` be used to specify an exponent in floating-point numbers. Using `e` currently results in a cell parse error but should be supported as well.

**Comment by stevorobs3** [comment]
Both `E` and `e` are now supported for floating point numbers. Please see example data here - [float-example.zip](https://github.com/Swirrl/csv2rdf/files/13549260/float-example.zip)
