### ISSUE TITLE
Outputting URIs using separator argument doesn't give multiple triples

### ISSUE THREAD

**Issue by rossbowen** [Swirrl/csv2rdf#55]
When using the `separator` argument to attempt outputting multiple triples, the object of which is a URI, I don't get expected behaviour.

`example.csv`:
```csv
name,knows
Ross,"http://example.org/Alice*http://example.org/Bob*http://example.org/Charlie"
```

`example.csv-metadata.json`:
```json
{
    "@context": "http://www.w3.org/ns/csvw",
    "url": "example.csv",
    "tableSchema": {
        "columns": [
            {
                "titles": "name",
                "name": "name",
                "suppressOutput": true
            },
            {
                "titles": "knows",
                "name": "knows",
                "separator": "*",
                "propertyUrl": "foaf:knows",
                "valueUrl": "{knows}"
            }
        ],
        "aboutUrl": "https://example.org/{name}"
    }
}

```
Expected output
```ttl
<https://example.org/example> <http://www.w3.org/ns/prov#wasDerivedFrom>
    <http://example.org/Alice>, <http://example.org/Bob>, <http://example.org/Charlie> .
```

Actual output
```ttl
<https://example.org/Ross> <http://xmlns.com/foaf/0.1/knows>
    <http://example.org/Alice,http://example.org/Bob,http://example.org/Charlie> .
```

Note that the `*` separator has been converted to a `,`. I've tried a few different choices for separators and the behaviour remains the same, so I don't believe it's caused by my specific choice of `*`.

When removing the `separator` argument, I do get three triples the object of which is a string, as expected.

```ttl
<https://example.org/Ross> <http://xmlns.com/foaf/0.1/knows> "http://example.org/Alice",
    "http://example.org/Bob", "http://example.org/Charlie" .
```

**Comment by Robsteranium** [comment]
I believe this is the expected behaviour based upon the URI template spec.

See the [examples here of list variable expansion](https://datatracker.ietf.org/doc/html/rfc6570#page-21).

Useful for building URL params, but less so for URIs where I had also hoped to see the behaviour you were expecting.

**Comment by rossbowen** [comment]
I'm looking at [section 4.6.8.6](https://www.w3.org/TR/csv2rdf/#generating-rdf) of the csv2rdf docs:
> Else, if the cell value is a list and the cell ordered annotation is true, then the cell value provides an ordered sequence of literal nodes for inclusion within the RDF output using an instance of rdf:List Vlist as defined in [rdf-schema]. This instance is related to the subject using the predicate P; emit the triples defining list Vlist plus the following triple:
> - subject: node S 
> - predicate: P
> - object: node Vlist


and a `list` is defined [here](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#dfn-cell-value-list):

>if the column separator annotation is not null, the cell value is a list of values; set the list annotation on the cell to true, and create the cell value created by:
if the normalized string is the same as any one of the values of the column null annotation, then the resulting value is null.
split the normalized string at the character specified by the column separator annotation.
unless the datatype base is string or anyAtomicType, strip leading and trailing whitespace from these strings.
applying the remaining steps to each of the strings in turn.

Helpful to get extra eyes on it - am I expecting the wrong behaviour?

**Comment by Robsteranium** [comment]
It looks like 4.6.8.6 is about literals not nodes. At this branch in the if-statement started in 4.6.8.4 the `valueUrl` is null.

**Comment by Robsteranium** [comment]
I'd hoped the same thing again @rossbowen!

This is particularly frustrating as you otherwise need to duplicate rows or create another table.

Maybe we should gather a list of things we wish were possible with csvw (like permitting extensions to the `@context`)? We could provide this as feedback to the w3c or use it to design our own extensions.
