### ISSUE TITLE
Some metadata is ignored. E.g. dc:description. Is it simply unsupported at present?

### ISSUE THREAD

**Issue by ash-mcc** [Swirrl/csv2rdf#64]
Hello Swirrl,

Some metadata is ignored by `csv2rdf` - i.e. there is no trace of it in the output (.ttl) files.

E.g. elements tagged with Dublin Core's `dc:description`. 

Is it simply unsupported at present? (Or have I missed some non obvious run option?)

Thanks, Ash

**Comment by Robsteranium** [comment]
Hello! Indeed there is an undocumented run option called "mode"! Sorry I thought we'd documented this.

The csvw specification provides 2 modes:

- Minimal mode gives you the triples from the CSV cells only.
- Standard mode also includes triples from the JSONLD annotation and an RDF representation of the source tables (with `csvw:Row` resources etc).

We've added an "annotated mode" that gives you the CSV and JSONLD annotation triples but not the `csvw:Row` resources etc. I suspect this is what you'll want.

From the cli you can do:

`csv2rdf -m annotated ...`

We probably ought to add some docs for CLI use and extend the [options section of the library documentation] (https://github.com/Swirrl/csv2rdf/blob/master/doc/library.md#options) to explain the choice of modes.

**Comment by ash-mcc** [comment]
Hi Robin ...thank you. The `-m annotated` option is indeed documented (sorry). 
An error of mine (a missing `@id`) was _masking_ its effect.
BTW, `csv2rdf` is a useful tool!
Cheers, Ash
